### ISSUE TITLE
Visiting the current URL doesn't reload the turbo frame

### ISSUE THREAD

**Issue by janko** [hotwired/turbo#269]
I have a link that points to the current URL (acting as a reload button), and it targets a turbo frame.

Clicking on the link the first time works; the frame is reloaded, and the `src` value of the frame is updated. Clicking on the link the second time doesn't work, there are no HTTP requests being made, and the frame is not reloaded.

I'm assuming it's because Turbo doesn't detect that `src` has changed, since it's the same link. However, this is not how regular links behave, you can always visit the current page, so I think it would make sense for Turbo to have the same behaviour.

Possibly related to https://github.com/hotwired/turbo/issues/249#issuecomment-830124904 and https://github.com/hotwired/turbo/issues/202.

**Comment by tleish** [comment]
While there is a bug in Turbo where frame visit to url A, url B and url A.  The last url A should be loaded, but nothing happens.

In the case you are suggesting: A visit to Turbo frame url A and then url A.  I see this as a feature, not a bug.

Turbos caching strategy avoids sending same requests to the server with turbo-frames.  Since the URL does not change, turbo makes a caching decision to not resend the request again and instead use the cached version.  If you want to force a reload, there are 2 fairly simple workarounds that I'm aware of.

1. Change the url with each click (e.g. add a timestamp or random string to the url)
2. Clear the turbo-frame src attribute after each time the frame is loaded with content.

**Comment by janko** [comment]
Thanks for the reply. We initially used the approach of clearing the `src` first, but then we switched to adding a timestamp to the URL.

However, I don't understand in which scenarios is this kind of caching useful. Personally, I would expect caching to only happen based on caching-related HTTP response headers.

I actually feel like this unexpected behaviour is coming from Turbo Frames possibly being designed to only watch for `src` changes on the frame, considering that [`navigateFrame`](https://github.com/hotwired/turbo/blob/aae03ada8be4b46899330364d712cc1ae57f2400/src/core/frames/frame_controller.ts#L239-L242) only changes the frame's `src`. In this case it's obvious there is a limitation of not detecting reloads.

**Comment by Bramjetten** [comment]
I don't understand why reloading the current URL is not allowed. This behaviour is counterintuitive to me. Adding a timestamp works as a temporary workaround. Reloading a frame can be useful to easily reset a frame's state initial state.

**Comment by rainerborene** [comment]
I think this cache mechanism should be optional and configurable. I'm using modals with `turbo-frame` but after the latest update it doesn't work anymore.

**Comment by CKolkey** [comment]
A `reload()` function for turbo frames was recently merges into master, so my solution to this was to wire a button element up to a stimulus controller that executes this `this.element.closest('turbo-frame[src]')?.reload()`

**Comment by rainerborene** [comment]
@CKolkey I will try that solution. But that feature differs from the default behavior of `frame` native tag. shouldn't it be reconsidered  to match the same browser behavior? ping @dhh

**Comment by en30** [comment]
I am experimenting to fix this issue in a branch, https://github.com/en30/turbo/tree/navigate-frame-to-src-url, which  I have not made into a PR yet.
In my app, this works for now, but I am not sure the change breaks a part that is not written as a test.

**Comment by dhh** [comment]
Fixed via https://github.com/hotwired/turbo/pull/349

**Comment by spohlenz** [comment]
Is anyone still seeing this issue even with 7.0.0-rc.2? Or perhaps I am just misunderstanding how this is meant to be working.

I have been playing with a demo app that is meant to refresh the time (via a turbo frame) when a link is clicked. The first click updates the time but clicking again does not (and does not trigger any additional requests). I don't see why this shouldn't work though.

`index.html.erb`:
```erb
<%= link_to "Update Time", time_path, data: { turbo_frame: "time" } %>
<turbo-frame id="time"></turbo-frame>
```

`time.html.erb`:
```erb
<turbo-frame id="time">
  <%=l Time.current %>
</turbo-frame>
```

I have uploaded my demo application to https://github.com/spohlenz/TurboFrameReload.

Along with the example above, I've included the Stimulus controller that I am currently using as a workaround which simply resets the turbo frame `src` after loading. It would be nice to be able to avoid this however.

`reset_frame_controller.js`:
```js
import { Controller } from 'stimulus'

export default class extends Controller {
  connect() {
    this.element.addEventListener('turbo:frame-load', () => {
      this.element.src = ''
    })
  }
}
```

**Comment by kirillplatonov** [comment]
@spohlenz it seems like reloading is not working for outer frame links. Only with inner links:
```erb
<turbo-frame target="time">
  <%= link_to "Update Time", time_path %>
</turbo-frame>
<turbo-frame id="time"></turbo-frame>
```

I missed that during testing. Working on a fix.

P.S. Thanks for the demo app. It was very helpful to reproduce the bug 🙏

**Comment by kirillplatonov** [comment]
Fixed in https://github.com/hotwired/turbo/pull/360

**Comment by spohlenz** [comment]
Thank you @kirillplatonov for fixing that so quickly. I can confirm it is working as I would expect now in 7.0.0-rc.3.
