### ISSUE TITLE
Links with method="post" and CORS issues

### ISSUE THREAD

**Issue by boardfish** [hotwired/turbo#74]
When I use the `link_to` helper with `method: :post` set, Turbo handles this as though it were a form. It issues a `fetch` request. If the response returned from this request is a 302 redirect to another host, CORS issues are encountered.

```
<a data-turbo="false" rel="nofollow" data-method="post" href="/auth/github">Connect GitHub</a>
```

I encountered this when doing something similar to #45 - the `link_to` helper creates links that redirect to third party services after `POST`ing to an endpoint on my app. When this is done without XHR, it's not an issue, but CORS issues arise with XHR, most likely because the redirect URLs are on external hosts (e.g. github.com).

Setting `data-turbo="false"` doesn't change or prevent this behavior, which is particularly unusual. In the meantime, I'm using `button_to(<text>, <link>, form: { 'data-turbo' => false })` as suggested in that thread. However, `a` and `button` are semantically different in HTML, so it's important this gets fixed for the sake of accessibility.

**Comment by sstephenson** [comment]
We just released [7.0.0-beta.2](https://github.com/hotwired/turbo/releases/tag/v7.0.0-beta.2) which allows you to opt out of form submissions with `data-turbo="false"`.

**Comment by boardfish** [comment]
Testing this now for my use case. I'll close if it rectifies my issue.

**Comment by boardfish** [comment]
Upgraded to the new beta and the issue remains, unfortunately.

**Comment by timonweb** [comment]
@boardfish same here. Updated my button code to:

```
<button data-turbo="false" type="submit" name="subscribe" class="button is-medium is-black is-outlined is-fullwidth">Subscribe 🚀</button>
```

And it doesn't work :(

**Comment by dhh** [comment]
It's not the button that needs data-turbo="false", it's the form that button belongs to.

**Comment by boardfish** [comment]
That's correct for buttons, but the link in the OP doesn't have a surrounding form. The `data-method` attribute controls the request method. I think this particular case is using `fetch` regardless of whether Turbo is enabled or not.

**Comment by dhh** [comment]
Ah yeah, then that's a bug. Turbo shouldn't be dealing with links that have data-turbo=false. cc @sstephenson

**Comment by boardfish** [comment]
@timonweb Your button should look like this:

```html
<form data-turbo="false" method="post" action="/subscribe">
  <input class="button is-medium is-black is-outlined is-fullwidth" name="subscribe" type="submit" value="Subscribe 🚀">
</form>
```

If you're on Rails, use a form helper:

```html.erb
    <%= button_to 'Subscribe 🚀', '/subscribe', class: 'button is-medium is-black is-outlined is-fullwidth',  name: 'subscribe', form: { 'data-turbo': false } %>
```

Hope that helps!

**Comment by timonweb** [comment]
@boardfish @dhh moved `data-turbo="false"` to the form tag and it works great now, thanks!
