### ISSUE TITLE
Content Security Policy support

### ISSUE THREAD

**Issue by mbardelmeijer** [hotwired/turbo#809]
We're trying to implement a CSP with Turbo.JS enabled. We're running into issues with `new DOMParser().parseFromString(html, "text/html")`, called from the `PageSnapshot` -> `fromHTMLString`

Is CSP supported officially by Turbo? If so, how can we implement this? We can disable the `nonce` to allow `unsafe-inline` on the `style` side which works, but not perfect.

```
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 'nonce-x5vJxhLYnMk87cAFBQAZyQengQlkiLU0IV56zb9q' 'unsafe-eval' https://rsms.me/inter/inter.css". Either the 'unsafe-inline' keyword, a hash ('sha256-Zt/lJRM6BFxPXh6Z2Wd3uSMAEMQJFCEyHj3wv0AnITY='), or a nonce ('nonce-...') is required to enable inline execution.

parseHTMLDocument @ app.aeffb485.js:423
fromHTMLString @ app.aeffb485.js:1594
(anonymous) @ app.aeffb485.js:1803
render @ app.aeffb485.js:1981
```

**Comment by stof** [comment]
Is there any recommendation about how to use Turbo with CSP when needing nonce-based rules ?

**Comment by rbclark** [comment]
I am using the following CSP with my rails applications:

```ruby
# Be sure to restart your server when you modify this file.

# Define an application-wide content security policy.
# See the Securing Rails Applications Guide for more information:
# https://guides.rubyonrails.org/security.html#content-security-policy-header

Rails.application.configure do
  config.content_security_policy do |policy|
    policy.default_src :self, :https
    policy.font_src :self, :https
    policy.img_src :self, :https, :data # data may be unnecessary for your use case.
    policy.object_src :none
    policy.script_src :self, :https
    policy.style_src :self, :https
    # Specify URI for violation reports
    # policy.report_uri "/csp-violation-report-endpoint"
  end

  # Generate session nonces for permitted importmap and inline scripts
  config.content_security_policy_nonce_generator = ->(request) { request.session.id.to_s }
  config.content_security_policy_nonce_directives = %w[script-src style-src]

  # Report violations without enforcing the policy.
  # config.content_security_policy_report_only = true
end
```

The main difference between this and rails default is that`style-src` is necessary for turbo, see https://github.com/hotwired/turbo/issues/704 for more information.

I've run into a few situations where the error for the CSP looks like it is coming from Turbo but is actually coming from Turbo trying to render my code. I've generally been able to find the actual source by forcing a full refresh on whatever page is causing the error which causes the page to not be rendered by turbo and therefore generally causes a better error message.

**Comment by tvongaza** [comment]
I am running into the same issue as @mbardelmeijer. I've tried @rbclark CSP settings without luck.

From my debugging I believe the issue lies in this section of code: https://github.com/hotwired/turbo/blob/main/src/core/frames/frame_controller.ts#L389

And how it interacts with the `parseHTMLDocument` code: https://github.com/hotwired/turbo/blob/4593d06ce58d17af5b17495ad8524eaa9bc2f5d2/src/util.ts#L70

I've got a frame with ownerDocument that looks like the follow:
```
> frame.ownerDocument.documentElement.outerHTML
< `<html><head><style type="text/css">.turbo-progress-bar {\n  position: fixed;\n  display: block;\n  top: 0;\n  left: 0;\n  height: 3px;\n  background: #0076ff;\n  z-index: 2147483647;\n  transition:\n    width 300ms ease-out,\n    opacity 150ms 150ms ease-in;\n  transform: translate3d(0, 0, 0);\n}\n</style>\n...`
```

If I manually check the Progress Bar inline style tag I get: 
```
> frame.ownerDocument.documentElement.querySelector("style").nonce
< '7f1811fb66c0afe93d7f618c1e766ef3'
```

The code serializes it for the Snapshot with the [outerHTML](https://github.com/hotwired/turbo/blob/main/src/core/frames/frame_controller.ts#L389) call and later it gets [parsed](https://github.com/hotwired/turbo/blob/4593d06ce58d17af5b17495ad8524eaa9bc2f5d2/src/util.ts#L70). At that point the style tag no longer retains it's nonce and the browser starts to complain about the CSP ("Refused to apply inline style ...").

We can test this out if we add a break point to the frame_controller when we set the responseHTML.
```
> html = frame.ownerDocument.documentElement.outerHTML

> newHtml =  new DOMParser().parseFromString(html, "text/html")
< Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' https: 'nonce-7f1811fb66c0afe93d7f618c1e766ef3'". Either the 'unsafe-inline' keyword, a hash ('sha256-C0gvgRBNF6Oc8gXG6w1eJon5YCMCelsuA+H5IQ1YSEk='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.
< '<style type="text/css">.turbo-progress-bar {\n  position: fixed;\n  display: block;\n  top: 0;\n  left: 0;\n  height: 3px;\n  background: #0076ff;\n  z-index: 2147483647;\n  transition:\n    width 300ms ease-out,\n    opacity 150ms 150ms ease-in;\n  transform: translate3d(0, 0, 0);\n}\n</style>'

> newHtml.querySelector("style").nonce
< ''
```

I'm assuming that the snapshot's html style tag should have the nonce set but it is getting lost? Or is there a CSP policy that allows for `new DOMParser().parseFromString(html, "text/html")` to safely parse html with inline styles that I maybe missing?

**Comment by MaksJS** [comment]
Since I've upgraded to Rails 7.1.rc and added `style-src` to `content_security_policy_nonce_directives` I also have this issue. It might becomes true for newly generated Rails 7.1 apps.

**Comment by KyleRego** [comment]
I ran into a very similar issue today, but it was fixed by doing a hard refresh on the browser.

**Comment by KyleRego** [comment]
Doing a refresh once was not the whole story as it kept happening. I think a solution in my case is to add <meta name="turbo-cache-control" content="no-cache"> (from the Turbo Handbook) to the top-level layout of the app

**Comment by rbclark** [comment]
> turbo-cache-control" content="no-cache

This will make your application not do any caching which may not be ideal. There is likely an underlying cause.

**Comment by KyleRego** [comment]
Good call, neither of my two comments above were really correct solutions. I waited a bit to say, but I think my issue was I had this line different - `config.content_security_policy_nonce_generator = ->(request) { request.session.id.to_s }`

**Comment by tvongaza** [comment]
Bit more digging into the code in regards to the comment https://github.com/hotwired/turbo/issues/809#issuecomment-1540946066.

For context, we are using Vite and their HMR of styles inlines the style sheets while working in development. We are attempting our dev environment to use a stricter CSP without `unsafe-inline` for styles.  The initial page load properly sets the CSP nonce for both the inline vite HMR style tags and the Turbo progress bar style tags.

However when you navigate with turbo, it will load the last page from cache to smartly add things like style sheets to the head, and this is where we run into the CSP issue, specially relating to `new DOMParser().parseFromString(html, "text/html");` where `html` is the cached page.

If one adds code to munge the raw html string to add the current pages CSP nonce to the style element's you can mostly getting working before the DOMParser gets to it. But this feels brittle and error prone.

There is a related open chromium issue with this exact problem which I believe is related: https://bugs.chromium.org/p/chromium/issues/detail?id=1148221

Example:
```
function parseHTMLDocument(html = "") {
    // parse our csp nonce
    const cspNonce = getMetaContent("csp-nonce");
    // remove all instances of 'nonce=""'
    const htmlWithNonce = html.replace(/nonce=""/g, "")
        // replace all instance of '<style type="text/css"' with <style type="text/css" nonce="cspNonce"
        .replace(/<style type="text\/css"/g, `<style type="text/css" nonce="${cspNonce}"`);

    return new DOMParser().parseFromString(htmlWithNonce, "text/html");
}
```

**Comment by tvongaza** [comment]
After a bit more digging I tracked this back to https://bugs.chromium.org/p/chromium/issues/detail?id=1148221, which triggers with Turbo tries to load up the cached HTML even if we aren't directly using it, thus things like the inline injected progress bar style sheet will trigger a CSP warning despite them never actually being used on the page.

That said, I was able to get a stricter `style_src` CSP working with Turbo. It requires setting a hash for the content of the injected progress bar style sheet contents to flag it as safe.

Using https://report-uri.com/home/hash for the contents at https://github.com/hotwired/turbo/blob/main/src/core/drive/progress_bar.js#L8 we get a hash of `WAyOw4V+FqDc35lQPyRADLBWbuNK8ahvYEaQIYF1+Ps=`:
```
.turbo-progress-bar {
  position: fixed;
  display: block;
  top: 0;
  left: 0;
  height: 3px;
  background: #0076ff;
  z-index: 2147483647;
  transition:
    width 300ms ease-out,
    opacity 150ms 150ms ease-in;
  transform: translate3d(0, 0, 0);
}

```

Updating our CSP as follows will allow turbo navigation to work for me without a CSP warning:
```
      policy.style_src :self, :https,
        "'sha256-WAyOw4V+FqDc35lQPyRADLBWbuNK8ahvYEaQIYF1+Ps='" # Turbo progress bar stylesheet
```

Of note, we are using some legacy JS which sets style tags (ie for dropdown positioning) which also violates the `style_src` CSP setting. We can break our `style_src_elem` and `style_src_attr` as follows, which lets us stay as strict as possible on the `style_src_elem`:

```
      policy.style_src_elem :self, :https,
        "'sha256-WAyOw4V+FqDc35lQPyRADLBWbuNK8ahvYEaQIYF1+Ps='" # Turbo progress bar stylesheet
      policy.style_src_attr :unsafe_inline                      # Some JS libraries sets style attributes for drop downs
```

**Comment by tvongaza** [comment]
I think this issue can be closed. The progress bar style sheet issue was resolved with https://github.com/hotwired/turbo/commit/ed72ba16bc23dcccd88e0ab76ba72cfef82cd599 in 7.3.

**Comment by DavidPetrasek** [comment]
I still get this error in Firefox:
`Content-Security-Policy: The page’s settings blocked an inline style (style-src-elem) from being applied because it violates the following directive: “style-src 'self' https://www.gstatic.com https://fonts.googleapis.com” global-DOXhD6tx.js:29:347`
and Chrome:
`Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' https://www.gstatic.com https://fonts.googleapis.com". Either the 'unsafe-inline' keyword, a hash ('sha256-WAyOw4V+FqDc35lQPyRADLBWbuNK8ahvYEaQIYF1+Ps='), or a nonce ('nonce-...') is required to enable inline execution.`

The error goes away when adding the hash as proposed by @tvongaza 

I use these versions:
....
├── @hotwired/stimulus@3.2.2
├── @hotwired/turbo@8.0.4
├── @symfony/stimulus-bridge@3.2.2
├── @symfony/ux-turbo@0.1.0 -> ./vendor/symfony/ux-turbo/assets
....
├── vite-plugin-stimulus-hmr@3.0.0
├── vite-plugin-symfony@6.4.7
└── vite@5.3.2

**Comment by likeuwill** [comment]
This issue still exists with Turbo `8.0.19`

![Image](https://github.com/user-attachments/assets/a65a52ff-fe22-457c-a336-b6e0c5c0ca51)
![Image](https://github.com/user-attachments/assets/8e0061b2-71aa-41f0-b879-058c08c8d61b)
![Image](https://github.com/user-attachments/assets/0e7a9647-f18e-4cd9-9607-00d225063389)
